### ISSUE TITLE
Backspace not working correctly

### ISSUE THREAD

**Issue by KateReller** [Stone-Red-Code/DiscordCLI#3]
I don't know if this is a user error, but DiscordCLI switches the cursor to overwrite mode.

**Comment by Stone-Red-Code** [comment]
Could you elaborate?

**Comment by KateReller** [comment]
https://streamable.com/9yhh3c

**Comment by Stone-Red-Code** [comment]
Very interesting. Which OS are you using?

**Comment by KateReller** [comment]
Arch Linux.

**Comment by Stone-Red-Code** [comment]
Ok it looks like it's a terminal issue. I just tried it on Kali with different terminal emulators and in some it worked fine and in some backspace didn't work at all.

**Comment by Stone-Red-Code** [comment]
Please tell me if it worked. If it didn't the issue will be reopened
