### ISSUE TITLE
"The required library hostfxr.dll could not be found"

### ISSUE THREAD

**Issue by KateReller** [Stone-Red-Code/DiscordCLI#4]
I extracted all of the files into a folder then ran DiscordCLI.exe in the terminal. Then this error comes up.
I'm on Arch Linux, and I have installed the `dotnet-runtime` package.

```
A fatal error occurred, the required library hostfxr.dll could not be found in [Z:\usr\share\dotnet\host\fxr\5.0.6]
0108:fixme:advapi:RegisterEventSourceW ((null),L".NET Runtime"): stub
0108:fixme:advapi:ReportEventW (00000000CAFE4242,0x0001,0x0000,0x000003ff,0000000000000000,0x0001,0x00000000,000000000019FB80,0000000000000000): stub
0108:err:eventlog:ReportEventW L"Description: A .NET application failed.\nApplication: DiscordCLI.exe\nPath: Z:\\home\\kate\\Downloads\\discord\\DiscordCLI.exe\nMessage: A fatal error occurred, the required library hostfxr.dll could not be found in [Z:\\usr\\share\\dotnet\\host\\fxr\\5.0.6]\n\n"
0108:fixme:advapi:DeregisterEventSource (00000000CAFE4242) stub
```

**Comment by Stone-Red-Code** [comment]
What's the output when you run the `dotnet --version` command?

**Comment by Stone-Red-Code** [comment]
> What's the output when you run the `dotnet --version` command?

**Comment by KateReller** [comment]
```
Could not execute because the application was not found or a compatible .NET SDK is not installed.
Possible reasons for this include:
  * You intended to execute a .NET program:
      The application '--version' does not exist.
  * You intended to execute a .NET SDK command:
      It was not possible to find any installed .NET SDKs.
      Install a .NET SDK from:
        https://aka.ms/dotnet-download
```

**Comment by Stone-Red-Code** [comment]
Oh. Can you try `dotnet --list-runtimes`?

**Comment by KateReller** [comment]
`Microsoft.NETCore.App 5.0.6 [/usr/share/dotnet/shared/Microsoft.NETCore.App]`

**Comment by Stone-Red-Code** [comment]
Hmm looks fine. The older version of `DiscordCLI` still works right?

**Comment by KateReller** [comment]
Version 0.3a works. Anything above does not.

**Comment by Stone-Red-Code** [comment]
Interesting. I'll look into it. 
Thanks for your patience.

**Comment by Stone-Red-Code** [comment]
Another question: How do you start the app?

**Comment by KateReller** [comment]
By making the DiscordCLI.exe executable and doing `./DiscordCLI.exe` in the terminal.
I'm pretty new to Linux in general so I could be doing things wrong.

**Comment by Stone-Red-Code** [comment]
Wym by: 
> making the DiscordCLI.exe executable

and you can try: `dotnet ./DiscordCLI.dll`

**Comment by KateReller** [comment]
Doing `chmod +x DiscordCLI.exe`.
And doing `dotnet ./DiscordCLI.dll` works.

**Comment by Stone-Red-Code** [comment]
Ok nice. I think I'll add platform specific builds in the next release again so you don't have to start the app like that.
